name = "DataLoaders"
uuid = "c95f3ad7-55be-4bf4-a3a9-d739e10a8a85"
authors = ["Nathan Barnes <npbarnes@alaska.edu>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
